import React from 'react';
import { Printer, Download, X, CheckCircle2 } from 'lucide-react';
import { Modal } from '../common/Modal';
import { FeeRecord } from '../../types/models';
import { KalamLogo } from '../common/KalamLogo';

interface ReceiptViewModalProps {
  isOpen: boolean;
  onClose: () => void;
  fee: FeeRecord | null;
}

export const ReceiptViewModal: React.FC<ReceiptViewModalProps> = ({
  isOpen,
  onClose,
  fee
}) => {
  if (!isOpen || !fee) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Official Fee Receipt"
      subtitle={`Receipt #${fee.receiptNumber || 'RCPT-PENDING'}`}
      maxWidth="lg"
    >
      <div className="space-y-6">
        
        {/* Printable Receipt Card */}
        <div id="kalam-printable-receipt" className="p-8 bg-slate-950 border border-slate-700/80 rounded-2xl shadow-xl text-slate-100 relative overflow-hidden">
          
          {/* Subtle Watermark Emblem Background */}
          <div className="absolute right-0 bottom-0 opacity-5 pointer-events-none translate-x-12 translate-y-12">
            <KalamLogo size={280} />
          </div>

          {/* Receipt Top Header */}
          <div className="flex items-center justify-between border-b border-slate-800 pb-5 mb-5">
            <KalamLogo size={56} showText subtitle="Study Centre & Digital Library • Gursarai, Jhansi (U.P.)" />
            <div className="text-right">
              <span className="text-[10px] uppercase font-bold tracking-widest text-slate-400 block">Official Receipt</span>
              <span className="font-mono text-sm font-extrabold text-amber-400 block mt-0.5">
                {fee.receiptNumber || 'RCPT-PREVIEW'}
              </span>
              <span className="text-[11px] text-slate-400 block mt-0.5">
                Date: {fee.paidDate ? new Date(fee.paidDate).toLocaleDateString() : new Date().toLocaleDateString()}
              </span>
            </div>
          </div>

          {/* Student Info Table */}
          <div className="grid grid-cols-2 gap-4 p-4 bg-slate-900/80 rounded-xl border border-slate-800/80 mb-6 text-xs">
            <div>
              <span className="text-[10px] text-slate-400 block uppercase font-semibold">Received From</span>
              <span className="text-sm font-bold text-slate-100 block mt-0.5">{fee.studentName}</span>
              <span className="font-mono text-amber-400 text-xs block mt-0.5">User ID: {fee.studentId}</span>
            </div>
            <div className="text-right">
              <span className="text-[10px] text-slate-400 block uppercase font-semibold">Payment Mode</span>
              <span className="font-semibold text-slate-200 block mt-0.5">{fee.paymentMode || 'Online UPI'}</span>
              <span className="text-[11px] text-emerald-400 font-semibold block mt-0.5 flex items-center justify-end gap-1">
                <CheckCircle2 size={13} />
                <span>Status: PAID</span>
              </span>
            </div>
          </div>

          {/* Fee Item Breakdown */}
          <div className="border border-slate-800 rounded-xl overflow-hidden mb-6 text-xs">
            <div className="flex justify-between bg-slate-850 px-4 py-2 font-bold text-slate-300 border-b border-slate-800 text-[11px] uppercase tracking-wider">
              <span>Description / Fee Head</span>
              <span>Amount (INR)</span>
            </div>
            <div className="flex justify-between px-4 py-3 bg-slate-900/40">
              <span className="font-medium text-slate-200">{fee.title}</span>
              <span className="font-mono font-bold text-slate-100">₹{fee.amount.toLocaleString('en-IN')}</span>
            </div>
            <div className="flex justify-between px-4 py-3 bg-slate-850 font-extrabold border-t border-slate-800 text-sm">
              <span className="text-amber-400">Total Paid Amount</span>
              <span className="text-amber-400 font-mono">₹{fee.amount.toLocaleString('en-IN')}</span>
            </div>
          </div>

          {/* Signatory & Disclaimer */}
          <div className="flex items-end justify-between pt-4 border-t border-slate-800/80 text-[11px] text-slate-400">
            <div>
              <p>Generated by Kalam Library Administration.</p>
              <p className="text-[10px] text-slate-500 mt-0.5">This is a computer-verified digital receipt.</p>
            </div>
            <div className="text-right">
              <div className="font-serif italic text-amber-300/80 mb-1 text-xs">Authorized Signatory</div>
              <div className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">Kalam Library Gursarai</div>
            </div>
          </div>

        </div>

        {/* Modal Buttons */}
        <div className="flex items-center justify-between pt-2 border-t border-slate-800">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-xs font-semibold text-slate-400 hover:text-slate-200 hover:bg-slate-800 rounded-lg cursor-pointer"
          >
            Close
          </button>
          <button
            type="button"
            onClick={handlePrint}
            className="px-4 py-2 text-xs font-bold text-slate-950 bg-amber-400 hover:bg-amber-300 rounded-lg shadow-sm flex items-center gap-1.5 cursor-pointer"
          >
            <Printer size={15} />
            <span>Print Receipt</span>
          </button>
        </div>

      </div>
    </Modal>
  );
};
